Header header

int32 target_id
geometry_msgs/Pose2D target_pose 			
geometry_msgs/Pose2D robot_pose  			

float64 target_lin_vel					
float64 robot_lin_vel   				
float64 robot_ang_vel					

geometry_msgs/Point target_goal 
geometry_msgs/Point target_local_goal 			

geometry_msgs/Vector3 target_global_force
geometry_msgs/Vector3 target_desired_force
geometry_msgs/Vector3 target_obstacle_force
geometry_msgs/Vector3 target_social_force
geometry_msgs/Vector3 target_group_force
geometry_msgs/Vector3 target_vref			
